// Book33 service worker -- offline app-shell cache.
// GENERATED by build-book33-synced.ps1 on every build; do not hand-edit --
// CACHE_VERSION changes every build so a fresh deploy always evicts the old cache.
var CACHE_VERSION = "b33-20260802094717";

self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE_VERSION).then(function (c) { return c.add("./"); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE_VERSION; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

// Navigations: try the network first (always get the freshest app + data when
// online), fall back to the cached shell when offline. Everything else
// (Google Fonts, the Supabase CDN script): cache-first once fetched, so a repeat
// offline load still has them -- opaque cross-origin responses are cached too
// (status is always 0 for those, so status===200 alone would skip them).
self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req).then(function (res) {
        caches.open(CACHE_VERSION).then(function (c) { c.put("./", res.clone()); });
        return res;
      }).catch(function () { return caches.match("./"); })
    );
    return;
  }
  e.respondWith(
    caches.match(req).then(function (cached) {
      return cached || fetch(req).then(function (res) {
        if (res && (res.status === 200 || res.type === "opaque")) {
          caches.open(CACHE_VERSION).then(function (c) { c.put(req, res.clone()); });
        }
        return res;
      }).catch(function () { return cached; });
    })
  );
});